### ISSUE TITLE
Class Contact - Implement Get & Set Functions

### ISSUE THREAD

**Issue by Didymus5** [Didymus5/CISC4305_Final_Project#4]
Contact.cpp needs get and set functions implemented

**Comment by tjoe1985** [comment]
void Contact::setTitle(string title)
{
	this->title = title;
}

string Contact::getTitle() const
{
	return title;
}

void Contact::setFirstName(string firstname)
{
	this->firstname = firstname;
}

string Contact::getFirstName() const
{
	return firstname;
}

void Contact::setLastName(string lastname)
{
	this->lastname = lastname;
}

string Contact::getLastName() const
{
	return lastname;
}

void Contact::setNationality(string nationality)
{
	this->nationality = nationality;
}

string Contact::getNationality() const
{
	return nationality;
}

void Contact::setState(string state)
{
	this->state = state;
}

string Contact::getState()const
{
	return  state;
}

void Contact::setCountry(string country)
{
	this->country = country;
}

string Contact::getCountry() const
{
	return   country;
}

void Contact::setEmail(string email)
{
	this->email = email;
}

string Contact::getCountry() const
{
	return    email;
}

void Contact::setPhoneNumber(string phonenumber)
{
	this->phoneNumber = phoneNumber;
}

string Contact::getPhoneNumber() const
{
	return    phoneNumber;
}

void Contact::setRace(string race)
{
	this->race = race;
}

string Contact::getRace()const
{
	return    race;
}
